---
name: OCI Image

on: 
  push:
    paths:
      - Dockerfile
      - cgit-pkg
      - rootfs
    branches:
      - main

env:
  BACKEND_IMAGE: ghcr.io/kriansa/gitty

jobs:
  build-and-push-image:
    name: Build and push the Docker image application
    runs-on: ubuntu-latest
    steps:
      - name: Set image tags
        id: image_tags
        run: |
          TAGS="${BACKEND_IMAGE}:latest,${BACKEND_IMAGE}:sha-${GITHUB_SHA::8}"
          echo ::set-output name=tags::${TAGS}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: backend
          push: true
          tags: ${{ steps.image_tags.outputs.tags }}
